# Generated by Django 5.1.4 on 2025-01-04 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='actor/')),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='actor/curriculum/')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='KasIndex.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='actor/video/')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo', to='KasIndex.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='actor/imagenes/')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='KasIndex.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('portada', models.ImageField(upload_to='actor/peliculas/')),
                ('plataforma', models.ImageField(max_length=50, upload_to='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='KasIndex.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('portada', models.ImageField(upload_to='actor/series/')),
                ('plataforma', models.ImageField(max_length=50, upload_to='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='KasIndex.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('Actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='KasIndex.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('portada', models.ImageField(upload_to='actor/television/')),
                ('televisora', models.ImageField(max_length=50, upload_to='')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='television', to='KasIndex.actor')),
            ],
        ),
    ]
