# Generated by Django 5.1.4 on 2025-01-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KasIndex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='especial',
            field=models.BooleanField(default=False),
        ),
    ]
