# Generated by Django 5.1.4 on 2025-01-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KasIndex', '0002_actor_especial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
        migrations.RenameModel(
            old_name='Peliculas',
            new_name='Pelicula',
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='Actor',
            new_name='actor',
        ),
    ]
